@startuml
skinparam shadowing false
skinparam classAttributeIconSize 0
skinparam classBackgroundColor #FFFFFF
skinparam classBorderColor #222222
skinparam arrowColor #222222
skinparam packageBorderColor #888888
skinparam defaultFontName Arial
skinparam classFontStyle bold
skinparam stereotypeFontSize 10
hide circle
hide members
hide stereotype
left to right direction

skinparam nodesep 35
skinparam ranksep 70
title UC21 - Mengubah Status Penanganan Laporan
class "C11 DasborAdmin" as C11
class "C21 ModerasiController" as C21
class "C26 Admin" as C26
class "C36 Laporan" as C36
class "C38 LogAudit" as C38
C11 --> C21
C21 ..> C26
C21 ..> C36
C21 ..> C38
C36 "1" -- "0..*" C38
@enduml
